name: Docker Image CI

on:
  push:
    branches: [ testcicd ]
  pull_request:
    branches: [ testcicd ]

jobs:

  build:	
    runs-on: ubuntu-latest	    
    steps:
    - uses: actions/checkout@v2	   
    - name: Build the Docker image	     
      run: docker-compose build
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: docker ps
