name: Docker Image CI

on:
  push:
    branches: [ testcicd ]
  pull_request:
    branches: [ testcicd ]

jobs:

  build:	
    runs-on: ubuntu-latest	    
    steps:
    - run: docker build --tag my-image:v1 .
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        image: my-image:v1
  
