name: Docker Image CI

on:
  push:
    branches: [ testcicd ]
  pull_request:
    branches: [ testcicd ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: testinitialcicd
        region: us-east-1
        tags: latest,${{ github.sha }}
        create_repo: true
